/// Emil Hedemalm
/// 2016-04-23
/// Enum of skills.

#ifndef ALL_SKILLS_ENUM
#define ALL_SKILLS_ENUM

#include "Class.h"
#include "Skill.h"

enum 
{
	/// CLASSLESS SKILLS,
	I_CAN_DO_IT = 0,
	RESTING, 
	BAZAAR,
	STEAL,
	DUAL_WIELD,
	CARTOGRAPHY,
	UNARMED_TRAINING,
	SHIELD_MASTERY,

	LONG_DISTANCE_ARCHERY = 15,
	BUY_N_SELL, 
	POLISH_GEAR,
	DUAL_WIELD_II,
	MAGIC_AFFINITY,
	UNARMED_TRAINING_II,

	RESTING_II = 30,
	UNARMED_TRAINING_III,
	LONG_DISTANCE_ARCHERY_II,
	DUAL_WIELD_III,
	STEAL_II,
	SHIELD_MASTERY_II,

	RESURRECT = 50,
	LONG_DISTANCE_ARCHERY_III,
	DUAL_WIELD_IV,
	UNARMED_TRAINING_IV,
	SHIELD_MASTERY_III,

	DUAL_WIELD_V = 60,
	UNARMED_TRAINING_V,

	DUAL_WIELD_VI = 70,
	UNARMED_TRAINING_VI,

	DUAL_WIELD_VII = 80,
	UNARMED_TRAINING_VII,

	UNARMED_TRAINING_VIII = 90,

	UNARMED_TRAINING_IX = 99,


	/// FIGHTER_SKILLS
	BERSERK = FIGHTER_SKILLS, // available at lvl 0.
	CHARGE,
	PROVOKE,
	DEFENDER,
	DEFENSIVE_TRAINING,
	OFFENSIVE_TRAINING, // all 5 available at lvl 1 to 5.

	DOUBLE_ATTACK = FIGHTER_SKILLS + 15,
	RUSH,
	DEFENSIVE_TRAINING_II,
	OFFENSIVE_TRAINING_II,
	OFFENSIVE_STANCE,

	TEMPO_TRAINING = FIGHTER_SKILLS + 30,
	GOAD,
	DOUBLE_ATTACK_II,
	WEAPON_BASH,
	RUSH_II,

	RUSH_III = FIGHTER_SKILLS + 50,
	STALWARD_DEFENDER, 

	/// ACOLYTE_SKILLS
	RESTORATION = ACOLYTE_SKILLS,
	SEAL_OF_PROTECTION,
	SEAL_WOUNDS,
	REFRESH,
	REMEDY,
	BANISH,

	SEAL_OF_PROTECTION_II = ACOLYTE_SKILLS + 15,
	MAGIC_SHIELD,
	REGENERATION,
	AETHER_EXPANSION,
	BANISH_II,

	SEAL_OF_PROTECTION_III = ACOLYTE_SKILLS + 30,
	BREATH_OF_LIFE, 
	SLOW,
	WARD_FROM_EVIL,
	BANISH_III,

	SEAL_OF_PROTECTION_IV = ACOLYTE_SKILLS + 50,
	SUBTLE_PRESENCE,
	STONESKIN,

	SEAL_OF_PROTECTION_V = ACOLYTE_SKILLS + 60,

	/// MONK_SKILLS
	INNER_POTENTIAL = MONK_SKILLS,
	STUNNING_FIST,
	BLOCKING,
	FOCUSED_BLOCK,
	COMBO,
	EVASION_TRAINING,

	BLOCKING_II = MONK_SKILLS + 15,
	KICK_ATTACKS,
	STUN_COMBO,
	STRENGTHENED_SKIN,
	DODGE_FOCUS,

	BLOCKING_III = MONK_SKILLS + 30,
	TAKE_DOWN,
	STRIKE_FOCUS,
	RAGING_FISTS,
	EVASION_TRAINING_II,

	BLOCKING_IV = MONK_SKILLS + 50,
	KICK_ATTACKS_II,
	CONTINUOUS_RUNNING,
	ONE_INCH_PUNCH,
	STRENGTHENED_SKIN_II,

	BLOCKING_V = MONK_SKILLS + 60,
	KICK_ATTACKS_III,
	UNARMED_ATTACK_SPEED,
	EVASION_TRAINING_III,
	THIRD_EYE,

	BLOCKING_VI = MONK_SKILLS + 70,
	UNARMED_ATTACK_SPEED_II,
	EVASION_TRAINING_IV,
	BOOST,

	BLOCKING_VII = MONK_SKILLS + 80,
	UNARMED_ATTACK_SPEED_III,

	BLOCKING_VIII = MONK_SKILLS + 90,
	UNARMED_ATTACKS_SPEED_IV,

	BLOCKING_IX = MONK_SKILLS + 100,

	ALL_SKILLS,

};

#endif
